package models;

public enum TypeConge {
    CONGE_MALADIE,
    CONGE_ACCIDENT_TRAVAIL,
    CONGE_MATERNITE,
    CONGE_PATERNITE,
    CONGE_DECES,
    CONGE_MARIAGE,
    CONGE_FORMATION,
    CONGE_PARENTAL,
    CONGE_JURY_COURT,
    CONGE_RECONVERSION,
    CONGE_LONGUE_MALADIE
}
